[workspace]
resolver = "3"
members = ["crates/domain", "crates/server"]

[workspace.package]
version = "1.2.0"
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.dependencies]
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
chrono-tz = "0.10"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
