// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Backup = { name: string, bytes: number, 
/**
 * RFC 3339 (from the file name).
 */
created_at: string, };
