// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the API shows of a calendar account.
 */
export type CalendarAccountView = { id: string, kind: string, url: string, username: string, has_password: boolean, 
/**
 * `new` (not synced yet), `ok` or `error`.
 */
status: string, last_sync_at: string | null, last_error: string | null, };
