// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One occurrence of a calendar event, as expanded from the cached iCalendar data.
 */
export type CalendarEvent = { id: string, user_id: string, calendar_id: string, uid: string, instance_key: string, title: string, location: string | null, all_day: boolean, 
/**
 * Timed events: RFC 3339 UTC.
 */
start_at: string | null, end_at: string | null, 
/**
 * All-day events: `YYYY-MM-DD`, end exclusive.
 */
start_date: string | null, end_date: string | null, 
/**
 * Blocks time (not marked free/transparent).
 */
busy: boolean, recurring: boolean, updated_at: string, deleted_at: string | null, rev: number, };
