// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Calendar = { id: string, account_id: string, user_id: string, href: string, name: string, color: string | null, user_color: string | null, enabled: boolean, 
/**
 * All-day events block the whole day.
 */
all_day_busy: boolean, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
