// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One item of a task's checklist (D-71).
 */
export type ChecklistItem = { 
/**
 * Stable within the list (client-chosen).
 */
id: string, text: string, done: boolean, };
