// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two overlapping items of a day. Ids are day entry ids (`task`), event ids (`event`)
 * or time block ids (`block`).
 */
export type ConflictView = { a: string, 
/**
 * `task`, `event` or `block`.
 */
a_kind: string, b: string, b_kind: string, 
/**
 * Overlap in minutes.
 */
minutes: number, };
