// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day at a glance, for the month calendar.
 */
export type DayGlance = { date: string, planned: number, done: number, 
/**
 * The day's mood (average), if logged.
 */
mood: number | null, journal: boolean, };
