// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Planning state of one day. No record (or a deleted one) means the day is unplanned.
 */
export type DayPlan = { id: string, user_id: string, date: string, 
/**
 * `draft` while the planning wizard is in progress, `planned` once confirmed.
 */
status: 'draft' | 'planned', 
/**
 * The wizard step to resume at.
 */
step: number, planned_at: string | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
