// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A day's reflection (SPEC §6.2b). Personal.
 */
export type DayRecord = { id: string, user_id: string, date: string, 
/**
 * Free text.
 */
journal: string, went_well: string, went_badly: string, tomorrow: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
