// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEvent } from "./CalendarEvent";
import type { DayRecord } from "./DayRecord";
import type { MetricDay } from "./MetricDay";
import type { RoutineDay } from "./RoutineDay";

/**
 * Everything about one day (SPEC §6.2b).
 */
export type DaySummary = { date: string, 
/**
 * Planned tasks by outcome. `carried` moved on to a later day unfinished.
 */
planned: number, done: number, missed: number, skipped: number, carried: number, open: number, 
/**
 * done / (done + missed + open); `null` when nothing counts.
 */
completion_rate: number | null, 
/**
 * Everything you completed that day, planned or not.
 */
completed_total: number, 
/**
 * Workflow steps completed that day.
 */
steps_done: number, routines: Array<RoutineDay>, 
/**
 * Calendar events of the day (titles and times are in the event list).
 */
events: Array<CalendarEvent>, focus_min: number, 
/**
 * For tasks done that day that had an estimate: estimated vs. recorded minutes.
 */
estimated_min: number, actual_min: number, metrics: Array<MetricDay>, record: DayRecord | null, };
