// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateBlock } from "./TemplateBlock";

/**
 * A reusable layout of time blocks (SPEC §6.8).
 */
export type DayTemplate = { id: string, owner_user_id: string, name: string, 
/**
 * ISO weekdays it applies to automatically: 1 = Monday … 7 = Sunday.
 */
weekdays: Array<number>, blocks: Array<TemplateBlock>, position: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
