// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEvent } from "./CalendarEvent";
import type { DayEntry } from "./DayEntry";
import type { DayPlan } from "./DayPlan";
import type { Task } from "./Task";

export type DayView = { date: string, today: string, 
/**
 * Planned entries for the date, in order.
 */
entries: Array<DayEntry>, 
/**
 * Tasks referenced by `entries`, plus open tasks due on or before the date.
 */
tasks: Array<Task>, 
/**
 * Planning state; `null` = unplanned.
 */
plan: DayPlan | null, 
/**
 * Calendar events on the date: timed ones overlapping it (local time) and all-day ones.
 */
events: Array<CalendarEvent>, 
/**
 * Minutes of the user's available window not taken by scheduled (timed) tasks or
 * busy calendar events.
 */
free_min: number, 
/**
 * Estimated minutes of open planned tasks without a time.
 */
planned_min: number, };
