// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A calendar event (every instance of a recurring one) assigned to a project (D-68).
 */
export type EventProject = { id: string, user_id: string, calendar_id: string, 
/**
 * The event's iCalendar UID (shared by all instances of a recurring event).
 */
uid: string, project_id: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
