// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FocusSession = { id: string, user_id: string, task_id: string | null, kind: 'work' | 'break', started_at: string, ended_at: string, minutes: number, 
/**
 * Ran its full length (vs skipped or stopped early).
 */
completed: boolean, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
