// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's focus timer as clients see it. Remaining time at `now` (ms) is
 * `length_min * 60000 - elapsed_ms - (running_since_ms ? now - running_since_ms : 0)`.
 */
export type FocusTimer = { task_id: string | null, phase: 'idle' | 'work' | 'short_break' | 'long_break', 
/**
 * Unix ms when the clock last started; `null` = paused or waiting to start.
 */
running_since_ms: number | null, elapsed_ms: number, length_min: number, 
/**
 * Completed work intervals since the last long break.
 */
cycle_done: number, rev: number, };
