// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FocusTimer } from "./FocusTimer";

export type FocusState = { timer: FocusTimer, 
/**
 * The server's clock (Unix ms), so clients can correct for clock differences.
 */
server_now: number, };
