// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoalReview = { id: string, goal_id: string, user_id: string, date: string, progress: number | null, note: string, created_at: string, };
