// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoalProgress = { goal_id: string, 
/**
 * What's shown: the override, else the derived value (0–1); `null` = nothing to measure yet.
 */
progress: number | null, 
/**
 * Derived from milestones and linked work, even when overridden.
 */
derived: number | null, milestones_done: number, milestones: number, tasks_done: number, tasks: number, };
