// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Milestone } from "./Milestone";

/**
 * A long-term goal (SPEC §6.10).
 */
export type Goal = { id: string, owner_user_id: string | null, owner_group_id: string | null, title: string, description: string, target_date: string | null, status: 'active' | 'paused' | 'achieved' | 'dropped', 
/**
 * 0–1, set by hand; `null` = derived from milestones and linked work.
 */
progress_override: number | null, milestones: Array<Milestone>, project_ids: Array<string>, task_ids: Array<string>, position: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
