// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMember } from "./GroupMember";

/**
 * A group of users (e.g. "Family") with its members (SPEC §6.4).
 */
export type Group = { id: string, name: string, created_by: string | null, members: Array<GroupMember>, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
