// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupMember = { user_id: string, display_name: string, username: string, 
/**
 * `owner` (can manage the group) or `member`.
 */
role: 'owner' | 'member', };
