// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A day's health check-in (D-75). Personal.
 */
export type HealthDay = { id: string, user_id: string, date: string, 
/**
 * `great`, `ok`, `unwell`, `sick` or `injured`.
 */
status: string, 
/**
 * What sickness (`cold`, `flu`, `fever`, `stomach`, `headache`, `other`) or where the
 * injury is (`back`, `neck`, `hand`, `arm`, `knee`, `foot`, `other`).
 */
kind: string | null, note: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
