// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogItem = { 
/**
 * When it happened (UTC). Missed items use the end of the day.
 */
at: string, 
/**
 * `completed`, `skipped`, `wont_do`, `missed`, `started`, `created`, `focus`, `planned`.
 */
kind: string, task_id: string | null, title: string, 
/**
 * Main project path of the task, if any.
 */
project: string | null, 
/**
 * Focus minutes.
 */
minutes: number | null, 
/**
 * The entry as a sentence, e.g. `Completed “Fix tap” (House)`.
 */
text: string, };
