// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The signed-in user as seen by themselves (and by admins in the user list).
 */
export type Me = { id: string, username: string, display_name: string, is_admin: boolean, timezone: string, day_end: string, };
