// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The signed-in user as seen by themselves (and by admins in the user list).
 */
export type Me = { id: string, username: string, display_name: string, is_admin: boolean, timezone: string, day_end: string, 
/**
 * BCP 47 language tag for dates and numbers; empty = the browser's language.
 */
locale: string, 
/**
 * First day of the week, ISO weekday (1 = Monday ... 7 = Sunday).
 */
week_start: number, 
/**
 * When the user plans: `evening` (plan tomorrow), `morning` (plan today) or `both`.
 */
plan_mode: 'evening' | 'morning' | 'both', plan_time_evening: string, plan_time_morning: string, 
/**
 * The part of the day counted as available time (`HH:MM`).
 */
day_window_start: string, day_window_end: string, };
