// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A metric's value on a day (its entries combined).
 */
export type MetricDay = { metric_id: string, value: number, 
/**
 * How many entries were combined.
 */
entries: number, };
