// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something a user tracks: mood, weight, or their own (sleep, water, steps…).
 */
export type MetricDefinition = { id: string, owner_user_id: string, 
/**
 * `mood` or `weight` for the built-ins.
 */
key: string | null, name: string, kind: 'number' | 'scale' | 'yes_no', 
/**
 * Weight is stored in kg.
 */
unit: string, scale_min: number | null, scale_max: number | null, 
/**
 * How several entries of a day combine.
 */
aggregate: 'latest' | 'average' | 'sum' | 'max', 
/**
 * `HH:MM`: a reminder if nothing is logged by then.
 */
reminder_time: string | null, archived: boolean, position: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
