// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetricEntry = { id: string, user_id: string, metric_id: string, 
/**
 * The logical day it counts for.
 */
date: string, 
/**
 * When it was logged.
 */
at: string, value: number, note: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
