// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A milestone of a goal.
 */
export type Milestone = { id: string, title: string, due_date: string | null, done: boolean, };
