// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NameMatch = { name: string, 
/**
 * `MM-DD` of each nameday of this name.
 */
dates: Array<string>, };
