// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedayDay } from "./NamedayDay";
import type { NamedaySource } from "./NamedaySource";

export type NamedayCalendar = { 
/**
 * `null` until a calendar has been loaded.
 */
source: NamedaySource | null, days: Array<NamedayDay>, };
