// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { 
/**
 * e.g. `plan_evening`, `plan_morning`.
 */
kind: string, title: string, body: string, 
/**
 * In-app path to open, e.g. `/plan/2026-10-07`.
 */
url: string, };
