// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One task an occasion creates.
 */
export type OccasionStep = { 
/**
 * `{name}` is replaced by the person's name.
 */
title: string, 
/**
 * Days from the occasion: −2 = two days before.
 */
offset_days: number, task_type_id: string, 
/**
 * Waits until the previous step is done (e.g. greet after buying the present).
 */
after_previous: boolean, };
