// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OccasionStep } from "./OccasionStep";

/**
 * What a kind of occasion creates for a user.
 */
export type OccasionTemplate = { id: string, owner_user_id: string, 
/**
 * `nameday` or `birthday`.
 */
kind: string, enabled: boolean, steps: Array<OccasionStep>, updated_at: string, rev: number, };
