// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Someone whose nameday and/or birthday matters to the user (SPEC §6.17).
 */
export type Person = { id: string, owner_user_id: string, 
/**
 * How tasks address them, e.g. "Mari (sister)".
 */
name: string, 
/**
 * The name as it appears in the nameday calendar.
 */
nameday_name: string | null, 
/**
 * `YYYY-MM-DD`, or `--MM-DD` when the year isn't known.
 */
birthday: string | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
