// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Somewhere tasks are done (SPEC §6.16). Coordinates are optional (for GPS detection).
 */
export type Place = { id: string, owner_user_id: string | null, owner_group_id: string | null, name: string, lat: number | null, lon: number | null, 
/**
 * How close (metres) counts as being there.
 */
radius_m: number, position: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
