// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, owner_user_id: string | null, owner_group_id: string | null, 
/**
 * Parent project for nested projects (`null` = top level).
 */
parent_id: string | null, name: string, color: string | null, 
/**
 * Shown with the colour to tell projects apart: circle, square, triangle, diamond,
 * hexagon or star (D-74).
 */
shape: string, position: string, archived_at: string | null, 
/**
 * Place given to new tasks created in this project.
 */
default_place_id: string | null, 
/**
 * What the project is about (plain text).
 */
description: string, 
/**
 * `active`, or `idea`: not started yet, so its tasks ask for no attention (D-72).
 */
status: string, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
