// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoutineDay = { series_id: string, title: string, done: boolean, 
/**
 * Current streak (as of now).
 */
streak: number, };
