// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A routine: a template that spawns one task per occurrence (SPEC §6.3).
 */
export type Series = { id: string, owner_user_id: string | null, owner_group_id: string | null, project_id: string | null, title: string, notes: string, 
/**
 * `repeat` (on the rule's dates), `anchored` (at a fixed time) or `flexible` (N per week/month).
 */
mode: 'repeat' | 'anchored' | 'flexible', 
/**
 * iCalendar RRULE without `RRULE:`, e.g. `FREQ=WEEKLY;BYDAY=MO,WE` (repeat/anchored).
 */
rrule: string | null, 
/**
 * First day (`YYYY-MM-DD`).
 */
dtstart: string, 
/**
 * Last day, inclusive; `null` = no end.
 */
until: string | null, 
/**
 * `HH:MM` for anchored routines.
 */
start_time: string | null, duration_min: number | null, 
/**
 * Flexible routines: how many times per window.
 */
times_per_window: number | null, window: 'week' | 'month' | null, task_type_id: string, estimate_min: number | null, difficulty: number | null, importance: number | null, urgency: number | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
