// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SeriesStats = { series_id: string, 
/**
 * Consecutive completed occurrences (or fully completed windows) up to now.
 */
streak: number, 
/**
 * Next occurrence date from today on (`YYYY-MM-DD`), if any.
 */
next_date: string | null, 
/**
 * Flexible routines: completed / total in the current window.
 */
window_done: number, window_total: number, };
