// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Suggestion } from "./Suggestion";
import type { Unplaced } from "./Unplaced";

export type SuggestedPlan = { suggestions: Array<Suggestion>, unplaced: Array<Unplaced>, };
