// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A suggested time for one task, with the reasons (codes: overdue, due_today,
 * due_tomorrow, due_soon {days}, expires_today, urgent, important, hard_in_hard_block,
 * easy_in_easy_block, earliest_free_time, estimate_assumed).
 */
export type Suggestion = { task_id: string, block_id: string | null, 
/**
 * `HH:MM`
 */
start_time: string, duration_min: number, reasons: Array<{ code: string, days?: number }>, };
