// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayEntry } from "./DayEntry";
import type { DayPlan } from "./DayPlan";
import type { Me } from "./Me";
import type { Project } from "./Project";
import type { Task } from "./Task";
import type { TaskType } from "./TaskType";

export type SyncResponse = { rev: number, full: boolean, me: Me, today: string, task_types: Array<TaskType>, projects: Array<Project>, tasks: Array<Task>, day_entries: Array<DayEntry>, day_plans: Array<DayPlan>, };
