// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Calendar } from "./Calendar";
import type { CalendarAccountView } from "./CalendarAccountView";
import type { CalendarEvent } from "./CalendarEvent";
import type { DayEntry } from "./DayEntry";
import type { DayPlan } from "./DayPlan";
import type { DayRecord } from "./DayRecord";
import type { DayTemplate } from "./DayTemplate";
import type { EventProject } from "./EventProject";
import type { FocusSession } from "./FocusSession";
import type { FocusTimer } from "./FocusTimer";
import type { Goal } from "./Goal";
import type { Group } from "./Group";
import type { HealthDay } from "./HealthDay";
import type { Me } from "./Me";
import type { MetricDefinition } from "./MetricDefinition";
import type { MetricEntry } from "./MetricEntry";
import type { OccasionTemplate } from "./OccasionTemplate";
import type { Person } from "./Person";
import type { Place } from "./Place";
import type { Project } from "./Project";
import type { Series } from "./Series";
import type { Task } from "./Task";
import type { TaskTemplate } from "./TaskTemplate";
import type { TaskType } from "./TaskType";
import type { TimeBlock } from "./TimeBlock";
import type { WorkflowTemplate } from "./WorkflowTemplate";

export type SyncResponse = { rev: number, full: boolean, me: Me, today: string, task_types: Array<TaskType>, projects: Array<Project>, tasks: Array<Task>, day_entries: Array<DayEntry>, day_plans: Array<DayPlan>, focus_timer: FocusTimer, focus_sessions: Array<FocusSession>, series: Array<Series>, places: Array<Place>, workflows: Array<WorkflowTemplate>, 
/**
 * Default tasks, yours and your groups' (D-71).
 */
task_templates: Array<TaskTemplate>, 
/**
 * Your connected calendar account, if any (always current).
 */
calendar_account: CalendarAccountView | null, calendars: Array<Calendar>, 
/**
 * Calendar event instances (a full sync covers the last 30 days onwards).
 */
events: Array<CalendarEvent>, 
/**
 * Calendar events assigned to projects.
 */
event_projects: Array<EventProject>, day_templates: Array<DayTemplate>, 
/**
 * Time blocks (a full sync covers the last 30 days onwards).
 */
time_blocks: Array<TimeBlock>, 
/**
 * Reflections (a full sync covers the last 30 days onwards).
 */
day_records: Array<DayRecord>, metrics: Array<MetricDefinition>, 
/**
 * Logged values (a full sync covers the last 400 days).
 */
metric_entries: Array<MetricEntry>, 
/**
 * Health check-ins (a full sync covers the last 400 days; D-75).
 */
health_days: Array<HealthDay>, 
/**
 * Your goals and your groups' goals.
 */
goals: Array<Goal>, 
/**
 * People whose namedays and birthdays matter to you.
 */
people: Array<Person>, 
/**
 * What each kind of occasion creates (always complete).
 */
occasion_templates: Array<OccasionTemplate>, 
/**
 * Your groups with their members (always complete).
 */
groups: Array<Group>, 
/**
 * The server's clock (Unix ms), so clients can correct for clock differences.
 */
server_now: number, };
