// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Calendar } from "./Calendar";
import type { CalendarAccountView } from "./CalendarAccountView";
import type { CalendarEvent } from "./CalendarEvent";
import type { DayEntry } from "./DayEntry";
import type { DayPlan } from "./DayPlan";
import type { DayTemplate } from "./DayTemplate";
import type { FocusSession } from "./FocusSession";
import type { FocusTimer } from "./FocusTimer";
import type { Group } from "./Group";
import type { Me } from "./Me";
import type { OccasionTemplate } from "./OccasionTemplate";
import type { Person } from "./Person";
import type { Place } from "./Place";
import type { Project } from "./Project";
import type { Series } from "./Series";
import type { Task } from "./Task";
import type { TaskType } from "./TaskType";
import type { TimeBlock } from "./TimeBlock";
import type { WorkflowTemplate } from "./WorkflowTemplate";

export type SyncResponse = { rev: number, full: boolean, me: Me, today: string, task_types: Array<TaskType>, projects: Array<Project>, tasks: Array<Task>, day_entries: Array<DayEntry>, day_plans: Array<DayPlan>, focus_timer: FocusTimer, focus_sessions: Array<FocusSession>, series: Array<Series>, places: Array<Place>, workflows: Array<WorkflowTemplate>, 
/**
 * Your connected calendar account, if any (always current).
 */
calendar_account: CalendarAccountView | null, calendars: Array<Calendar>, 
/**
 * Calendar event instances (a full sync covers the last 30 days onwards).
 */
events: Array<CalendarEvent>, day_templates: Array<DayTemplate>, 
/**
 * Time blocks (a full sync covers the last 30 days onwards).
 */
time_blocks: Array<TimeBlock>, 
/**
 * People whose namedays and birthdays matter to you.
 */
people: Array<Person>, 
/**
 * What each kind of occasion creates (always complete).
 */
occasion_templates: Array<OccasionTemplate>, 
/**
 * Your groups with their members (always complete).
 */
groups: Array<Group>, 
/**
 * The server's clock (Unix ms), so clients can correct for clock differences.
 */
server_now: number, };
