// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChecklistItem } from "./ChecklistItem";

/**
 * A default task (D-71): a ready-made task, e.g. "Do laundry" with its checklist.
 */
export type TaskTemplate = { id: string, owner_user_id: string | null, owner_group_id: string | null, title: string, notes: string, 
/**
 * Copied unticked into each new task.
 */
checklist: Array<ChecklistItem>, estimate_min: number | null, difficulty: number | null, importance: number | null, urgency: number | null, 
/**
 * `null` = the default type.
 */
task_type_id: string | null, project_id: string | null, place_id: string | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
