// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type Task = { id: string, owner_user_id: string | null, owner_group_id: string | null, assignee_user_id: string | null, project_id: string | null, title: string, notes: string, status: TaskStatus, position: string, due_date: string | null, estimate_min: number | null, difficulty: number | null, importance: number | null, urgency: number | null, actual_min: number, task_type_id: string, carry_count: number, 
/**
 * Set when work on the task began ("in progress" while the task is open).
 */
started_at: string | null, completed_at: string | null, completed_by: string | null, ext_source: string | null, ext_id: string | null, ext_url: string | null, 
/**
 * Where the task has to be done; `null` = anywhere.
 */
place_id: string | null, 
/**
 * The calendar event (instance) the task is for; only its owner can resolve it.
 */
event_id: string | null, 
/**
 * Other projects the task is also listed in (besides its main `project_id`).
 */
also_project_ids: Array<string>, 
/**
 * Tasks that must be finished first (SPEC §6.3b).
 */
depends_on: Array<string>, 
/**
 * A prerequisite is still open: not in the ready stack, can't be planned.
 */
blocked: boolean, 
/**
 * Minutes to wait after the last prerequisite is done (e.g. a machine running).
 */
wait_min: number | null, 
/**
 * While waiting: when the task becomes ready.
 */
ready_at: string | null, 
/**
 * Steps of a running workflow: the run, this step's number and the step count.
 */
workflow_instance_id: string | null, workflow_step: number | null, workflow_steps: number | null, 
/**
 * Set for occurrences of a routine.
 */
series_id: string | null, 
/**
 * Identifies the occurrence within its routine (a date, or window start + "#n").
 */
occurrence_key: string | null, 
/**
 * The day the occurrence is for (or the first day of its window).
 */
occurrence_date: string | null, 
/**
 * For "N times per week/month" routines: the last day of the window.
 */
window_end: string | null, 
/**
 * Waiting for a result (D-70): set while nothing needs doing.
 */
waiting_since: string | null, 
/**
 * When to check back. Still set after `waiting_since` clears: "check back now".
 */
check_back_at: string | null, 
/**
 * What's being waited for.
 */
waiting_note: string, 
/**
 * Who set the task waiting (gets the check-back reminder).
 */
waiting_by: string | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
