// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type Task = { id: string, owner_user_id: string | null, owner_group_id: string | null, assignee_user_id: string | null, project_id: string | null, title: string, notes: string, status: TaskStatus, position: string, due_date: string | null, estimate_min: number | null, difficulty: number | null, importance: number | null, urgency: number | null, actual_min: number, task_type_id: string, carry_count: number, completed_at: string | null, completed_by: string | null, ext_source: string | null, ext_id: string | null, ext_url: string | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
