// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskType = { id: string, key: string, name: string, day_end_behavior: 'carry' | 'expire' | 'window' | 'deadline', counts_for_streak: boolean, shows_overdue: boolean, shows_carry_count: boolean, builtin: boolean, deleted_at: string | null, rev: number, };
