// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type Task = { id: string, owner_user_id: string | null, owner_group_id: string | null, assignee_user_id: string | null, project_id: string | null, title: string, notes: string, status: TaskStatus, position: string, due_date: string | null, estimate_min: number | null, difficulty: number | null, importance: number | null, urgency: number | null, actual_min: number, task_type_id: string, carry_count: number, 
/**
 * Set when work on the task began ("in progress" while the task is open).
 */
started_at: string | null, completed_at: string | null, completed_by: string | null, ext_source: string | null, ext_id: string | null, ext_url: string | null, 
/**
 * Where the task has to be done; `null` = anywhere.
 */
place_id: string | null, 
/**
 * Other projects the task is also listed in (besides its main `project_id`).
 */
also_project_ids: Array<string>, 
/**
 * Set for occurrences of a routine.
 */
series_id: string | null, 
/**
 * Identifies the occurrence within its routine (a date, or window start + "#n").
 */
occurrence_key: string | null, 
/**
 * The day the occurrence is for (or the first day of its window).
 */
occurrence_date: string | null, 
/**
 * For "N times per week/month" routines: the last day of the window.
 */
window_end: string | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
