// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A block of a day template.
 */
export type TemplateBlock = { 
/**
 * The block's theme, e.g. "Deep work: hard tasks".
 */
title: string, 
/**
 * `HH:MM`
 */
start: string, end: string, 
/**
 * `hard`, `medium` or `easy`: what kind of task the planner puts here.
 */
energy: string | null, };
