// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time block on one day.
 */
export type TimeBlock = { id: string, user_id: string, date: string, title: string, start_time: string, end_time: string, energy: string | null, template_id: string | null, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
