// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Unplaced = { task_id: string, 
/**
 * `blocked` (waiting for a prerequisite) or `no_room` (with `minutes`).
 */
reason: { code: 'blocked' } | { code: 'no_room', minutes: number }, };
