// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Someone you can add to a group (every user of this install).
 */
export type UserSummary = { id: string, display_name: string, username: string, };
