// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of a workflow template.
 */
export type WorkflowStep = { 
/**
 * Stable id within the template (variants refer to it).
 */
id: string, title: string, estimate_min: number | null, 
/**
 * Wait this long after this step before the next one is ready (e.g. the machine runs).
 */
wait_min: number | null, difficulty: number | null, };
