// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A variant of a workflow: the template's steps minus `skip`.
 */
export type WorkflowVariant = { id: string, name: string, skip: Array<string>, };
