// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStep } from "./WorkflowStep";
import type { WorkflowVariant } from "./WorkflowVariant";

/**
 * A reusable multi-step chore (SPEC §6.3b), e.g. Laundry with variants per load.
 */
export type WorkflowTemplate = { id: string, owner_user_id: string | null, owner_group_id: string | null, name: string, description: string, 
/**
 * Project the steps go into (optional).
 */
project_id: string | null, steps: Array<WorkflowStep>, variants: Array<WorkflowVariant>, created_at: string, updated_at: string, deleted_at: string | null, rev: number, };
